global:
  scrape_interval: 60s
remote_write:
  - url: https://localhost:12345/agent/api/v1/metrics/instance/hosted-prometheus/write
scrape_configs:
  - job_name: node
    static_configs:
      - targets: ["localhost:9090"]
