global:
  scrape_interval: 60s

scrape_configs:
  - job_name: nodejs_app
    static_configs:
      - targets: ["localhost:4040"]

remote_write:
  - url: "https://localhost:12345/agent/api/v1/metrics/instance/hosted-prometheus/write"
