global:
  scrape_interval: 60s
remote_write:
  - url: URL
    basic_auth:
      username: 1854140
      password: TOKEN
scrape_configs:global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "nodejs_app"
    static_configs:
      - targets: ["localhost:4040"] # Adjust to the port your app runs on


  - job_name: node
    static_configs:
      - targets: ["localhost:4040"]
